python tree_lstm_artery.py --exp=exp --model=bi --cv=0 --cv_max=5 --device=cuda:0 --train=attack --prob=0.05
python tree_lstm_artery.py --exp=exp --model=bi --cv=0 --cv_max=5 --device=cuda:0 --train=attack --prob=0.075
python tree_lstm_artery.py --exp=exp --model=bi --cv=0 --cv_max=5 --device=cuda:0 --train=attack --prob=0.1
python tree_lstm_artery.py --exp=exp --model=bi --cv=0 --cv_max=5 --device=cuda:0 --train=attack --prob=0.125
python tree_lstm_artery.py --exp=exp --model=bi --cv=0 --cv_max=5 --device=cuda:0 --train=attack --prob=0.15
python tree_lstm_artery.py --exp=exp --model=bi --cv=0 --cv_max=5 --device=cuda:0 --train=attack --prob=0.175
python tree_lstm_artery.py --exp=exp --model=bi --cv=0 --cv_max=5 --device=cuda:0 --train=attack --prob=0.2
python tree_lstm_artery.py --exp=exp --model=bi --cv=1 --cv_max=5 --device=cuda:0 --train=attack --prob=0.05
python tree_lstm_artery.py --exp=exp --model=bi --cv=1 --cv_max=5 --device=cuda:0 --train=attack --prob=0.075
python tree_lstm_artery.py --exp=exp --model=bi --cv=1 --cv_max=5 --device=cuda:0 --train=attack --prob=0.1
python tree_lstm_artery.py --exp=exp --model=bi --cv=1 --cv_max=5 --device=cuda:0 --train=attack --prob=0.125
python tree_lstm_artery.py --exp=exp --model=bi --cv=1 --cv_max=5 --device=cuda:0 --train=attack --prob=0.15
python tree_lstm_artery.py --exp=exp --model=bi --cv=1 --cv_max=5 --device=cuda:0 --train=attack --prob=0.175
python tree_lstm_artery.py --exp=exp --model=bi --cv=1 --cv_max=5 --device=cuda:0 --train=attack --prob=0.2
python tree_lstm_artery.py --exp=exp --model=bi --cv=2 --cv_max=5 --device=cuda:0 --train=attack --prob=0.05
python tree_lstm_artery.py --exp=exp --model=bi --cv=2 --cv_max=5 --device=cuda:0 --train=attack --prob=0.075
python tree_lstm_artery.py --exp=exp --model=bi --cv=2 --cv_max=5 --device=cuda:0 --train=attack --prob=0.1
python tree_lstm_artery.py --exp=exp --model=bi --cv=2 --cv_max=5 --device=cuda:0 --train=attack --prob=0.125
python tree_lstm_artery.py --exp=exp --model=bi --cv=2 --cv_max=5 --device=cuda:0 --train=attack --prob=0.15
python tree_lstm_artery.py --exp=exp --model=bi --cv=2 --cv_max=5 --device=cuda:0 --train=attack --prob=0.175
python tree_lstm_artery.py --exp=exp --model=bi --cv=2 --cv_max=5 --device=cuda:0 --train=attack --prob=0.2
python tree_lstm_artery.py --exp=exp --model=bi --cv=3 --cv_max=5 --device=cuda:0 --train=attack --prob=0.05
python tree_lstm_artery.py --exp=exp --model=bi --cv=3 --cv_max=5 --device=cuda:0 --train=attack --prob=0.075
python tree_lstm_artery.py --exp=exp --model=bi --cv=3 --cv_max=5 --device=cuda:0 --train=attack --prob=0.1
python tree_lstm_artery.py --exp=exp --model=bi --cv=3 --cv_max=5 --device=cuda:0 --train=attack --prob=0.125
python tree_lstm_artery.py --exp=exp --model=bi --cv=3 --cv_max=5 --device=cuda:0 --train=attack --prob=0.15
python tree_lstm_artery.py --exp=exp --model=bi --cv=3 --cv_max=5 --device=cuda:0 --train=attack --prob=0.175
python tree_lstm_artery.py --exp=exp --model=bi --cv=3 --cv_max=5 --device=cuda:0 --train=attack --prob=0.2
python tree_lstm_artery.py --exp=exp --model=bi --cv=4 --cv_max=5 --device=cuda:0 --train=attack --prob=0.05
python tree_lstm_artery.py --exp=exp --model=bi --cv=4 --cv_max=5 --device=cuda:0 --train=attack --prob=0.075
python tree_lstm_artery.py --exp=exp --model=bi --cv=4 --cv_max=5 --device=cuda:0 --train=attack --prob=0.1
python tree_lstm_artery.py --exp=exp --model=bi --cv=4 --cv_max=5 --device=cuda:0 --train=attack --prob=0.125
python tree_lstm_artery.py --exp=exp --model=bi --cv=4 --cv_max=5 --device=cuda:0 --train=attack --prob=0.15
python tree_lstm_artery.py --exp=exp --model=bi --cv=4 --cv_max=5 --device=cuda:0 --train=attack --prob=0.175
python tree_lstm_artery.py --exp=exp --model=bi --cv=4 --cv_max=5 --device=cuda:0 --train=attack --prob=0.2
