python train_artery_pca.py --flow=attack --prob=0.05 --exp=exp/pca/CV0 --cv=0 --plot=True
python train_artery_pca.py --flow=attack --prob=0.075 --exp=exp/pca/CV0 --cv=0 --plot=True
python train_artery_pca.py --flow=attack --prob=0.1 --exp=exp/pca/CV0 --cv=0 --plot=True
python train_artery_pca.py --flow=attack --prob=0.125 --exp=exp/pca/CV0 --cv=0 --plot=True
python train_artery_pca.py --flow=attack --prob=0.15 --exp=exp/pca/CV0 --cv=0 --plot=True
python train_artery_pca.py --flow=attack --prob=0.175 --exp=exp/pca/CV0 --cv=0 --plot=True
python train_artery_pca.py --flow=attack --prob=0.2 --exp=exp/pca/CV0 --cv=0 --plot=True
python train_artery_pca.py --flow=attack --prob=0.05 --exp=exp/pca/CV1 --cv=1 --plot=True
python train_artery_pca.py --flow=attack --prob=0.075 --exp=exp/pca/CV1 --cv=1 --plot=True
python train_artery_pca.py --flow=attack --prob=0.1 --exp=exp/pca/CV1 --cv=1 --plot=True
python train_artery_pca.py --flow=attack --prob=0.125 --exp=exp/pca/CV1 --cv=1 --plot=True
python train_artery_pca.py --flow=attack --prob=0.15 --exp=exp/pca/CV1 --cv=1 --plot=True
python train_artery_pca.py --flow=attack --prob=0.175 --exp=exp/pca/CV1 --cv=1 --plot=True
python train_artery_pca.py --flow=attack --prob=0.2 --exp=exp/pca/CV1 --cv=1 --plot=True
python train_artery_pca.py --flow=attack --prob=0.05 --exp=exp/pca/CV2 --cv=2 --plot=True
python train_artery_pca.py --flow=attack --prob=0.075 --exp=exp/pca/CV2 --cv=2 --plot=True
python train_artery_pca.py --flow=attack --prob=0.1 --exp=exp/pca/CV2 --cv=2 --plot=True
python train_artery_pca.py --flow=attack --prob=0.125 --exp=exp/pca/CV2 --cv=2 --plot=True
python train_artery_pca.py --flow=attack --prob=0.15 --exp=exp/pca/CV2 --cv=2 --plot=True
python train_artery_pca.py --flow=attack --prob=0.175 --exp=exp/pca/CV2 --cv=2 --plot=True
python train_artery_pca.py --flow=attack --prob=0.2 --exp=exp/pca/CV2 --cv=2 --plot=True
python train_artery_pca.py --flow=attack --prob=0.05 --exp=exp/pca/CV3 --cv=3 --plot=True
python train_artery_pca.py --flow=attack --prob=0.075 --exp=exp/pca/CV3 --cv=3 --plot=True
python train_artery_pca.py --flow=attack --prob=0.1 --exp=exp/pca/CV3 --cv=3 --plot=True
python train_artery_pca.py --flow=attack --prob=0.125 --exp=exp/pca/CV3 --cv=3 --plot=True
python train_artery_pca.py --flow=attack --prob=0.15 --exp=exp/pca/CV3 --cv=3 --plot=True
python train_artery_pca.py --flow=attack --prob=0.175 --exp=exp/pca/CV3 --cv=3 --plot=True
python train_artery_pca.py --flow=attack --prob=0.2 --exp=exp/pca/CV3 --cv=3 --plot=True
python train_artery_pca.py --flow=attack --prob=0.05 --exp=exp/pca/CV4 --cv=4 --plot=True
python train_artery_pca.py --flow=attack --prob=0.075 --exp=exp/pca/CV4 --cv=4 --plot=True
python train_artery_pca.py --flow=attack --prob=0.1 --exp=exp/pca/CV4 --cv=4 --plot=True
python train_artery_pca.py --flow=attack --prob=0.125 --exp=exp/pca/CV4 --cv=4 --plot=True
python train_artery_pca.py --flow=attack --prob=0.15 --exp=exp/pca/CV4 --cv=4 --plot=True
python train_artery_pca.py --flow=attack --prob=0.175 --exp=exp/pca/CV4 --cv=4 --plot=True
python train_artery_pca.py --flow=attack --prob=0.2 --exp=exp/pca/CV4 --cv=4 --plot=True
